### ISSUE TITLE
Staking DApp pool address popup information

### ISSUE THREAD

**Issue by andogro** [poanetwork/blockscout#2211]
Some information in the pool address popup is inaccurate- similar to #2188 but only relates to popup rather than header.

### Environment

Following local setup from #2168.

### Steps to reproduce

Click on an active or inactive pool address:

Validator Information Box issues to address:
1. Delegors (should be **Delegators'**)
2. Stakes Ratio and Likelihood of becoming a Validator are different metrics (likelihood needs to account for Max # of Validators and adjust accordingly, if there are fewer than 19 eligible candidates with at least minimum stake then the likelihood is 100%)
3. Reward Precent (should be **Percent**) - should reflect actual percentage.
4. How Many Times ~~the~~ **this** Address ~~was~~ **has been** a Validator
5. How Many Times ~~the~~ **this** Address ~~was~~ **has been** banned
6. Number of Delegators and Delegators Staked Amount are different metrics (unsure if there are 9 delegators who each staked 1 token in this scenario - if so then this is correct)

**Comment by saneery** [comment]
1. fixed https://github.com/poanetwork/blockscout/pull/2246
2-3. I will create PR with calculating reward percent and likelihood
4-5. fixed here https://github.com/poanetwork/blockscout/pull/2215
6. Yes, in the test setup each delegator stakes 1 token

**Comment by goodsoft** [comment]
@andogro shouldn't the label from 1) be **Delegators'** (plural)? I suppose, it's a sum of all stakes that other delegators made.

**Comment by andogro** [comment]
yes, correct. thank you.

**Comment by goodsoft** [comment]
@andogro please let me know if any of listed issues are still relevant, or we can close this issue.

**Comment by andogro** [comment]
@goodsoft I am having difficulty compiling blockscout locally at the moment to double check these items, however I know the wording issues have been solved and I can add new items either to PR 2292 (see item #6 here for potential issue I will verify https://github.com/poanetwork/blockscout/pull/2292#issuecomment-517391758) or to Issue #2188 to consolidate these, so feel free to close.

**Comment by goodsoft** [comment]
Okay, I'll close this one then.
Would be great if you transferred all problems from 2188 that are not fixed yet to 2292 as well, so that there's a single source of issues.
